In [1]:
import numpy as np

In [2]:
A = np.array([[-2,  4, 0], [2, -5, 3], [2,  0, 6]])
B = np.array([[-2, -4, 6], [1,  0, 3], [1,  2 , -5]])
E = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
0.5 * A + 2 * B - E

array([[-6. , -6. , 12. ],
       [ 3. , -3.5,  7.5],
       [ 3. ,  4. , -8. ]])

In [2]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

def cumsum(A):
    #param A: np.array[m,n]
        

    result = np.cumsum(A, axis=1)
    return result

In [3]:
cumsum(A)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [5]:
B = A.copy()
a = 1

[[1, 2, 3], [7, 8, 9]]

In [21]:
B

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
A = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [24]:
B = np.bincount(A)

In [25]:
B

array([0, 3, 3, 4, 0, 2])

In [52]:
C = np.diff(A)

In [54]:
C

array([ 2,  1,  2,  1, -1,  1,  5,  1, -2,  2,  1])

In [49]:
A[np.flatnonzero(C)]

array([1, 2, 3, 1, 5, 2])

In [65]:
E = np.flatnonzero(C) + 1
E

array([ 1,  3,  5,  7,  9, 10])

In [62]:
start = np.array([0])

In [68]:
d = np.r_[0, A[:-1]]

In [69]:
d

array([0, 1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3])

In [71]:
d[np.flatnonzero(np.diff(d))]

array([0, 1, 2, 3, 1, 5, 2])